config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root "home#index"
  resources :home, only: [:index] do
    collection do
      get 'app_description'
    end
  end
  resources :signup, only: [:new, :create] do
    collection do
      get 'logout'
      get 'start_app'
    end
  end
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'category'
      get 'novel'
      get 'management'
      get 'economy'
      get 'finance'
      get 'it'
      get 'motivation'
      get 'talent'
      get 'etc'
      get 'reread_timing'
      get 'timing_knowledge'
      get 'timing_motivation'
      get 'timing_decision'
      get 'timing_stress'
      get 'timing_feel_down'
      get 'timing_lost_love'
      get 'timing_diversion'
      get 'timing_relax'
      get 'all_books'
      get 'read_books'
      get 'will_read_books'
      get 'follow_book'
      get 'followings'
      get 'followers'
      get 'read_count_books'
      get 'read_history'
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :books do
    resources :impressions
    collection do
      get 'search'
    end
    member do
      get 'follow_book_show'
    end
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  before_action :birthday_add, only: [:create]

  def new
    @user = User.new
  end

  def create
    # if params[:sns_auth] == 'true'
    #   pass = Devise.friendly_token
    #   params[:user][:password] = pass
    #   params[:user][:password_confirmation] = pass
    # end
    params[:user][:birth_day] = @birth_date.to_s
    @user = User.new(user_params)
    if @user.save
      sign_in User.find(@user.id) unless user_signed_in?
      redirect_to user_path(current_user.id)
    else
      render 'new'
    end
  end

  def logout; end

  def start_app; end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :password, :birth_day)
  end

  def birthday_add
    if params[:birth_day]["birth_day(1i)"].present? && params[:birth_day]["birth_day(2i)"].present? && params[:birth_day]["birth_day(3i)"].present?
      birthday = params[:birth_day]
      @birth_date = Date.new(birthday["birth_day(1i)"].to_i, birthday["birth_day(2i)"].to_i, birthday["birth_day(3i)"].to_i)
    end
  end
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/signup/logout.html.haml
.logout.main-font
  .logout__main.box-center
    = render "shared/content_top"
    .btn-box.display-flex
      .btn-box__user-new
        = link_to destroy_user_session_path, method: :delete, class:"black-link-btn text-line-none" do
          ログアウト
      .btn-box__back
        = link_to :back, class: "gray-btn margin-left-40 text-line-none" do
          もどる

app/views/signup/new.html.haml
.signup-new.main-font
  .signup-new__main.box-center
    = render "shared/content_top"
    = form_with(model: @user, url: signup_index_path(@user), method: :POST, local: true) do |f|
      .user-detail
        .user-detail__test
          ※テストアカウントがございます。ログインにお進みください。
        .user-detail__top.form-content
          ニックネーム
        .user-detail__nickname-input
          = f.text_field :nickname, placeholder: "> nickname", class:"text-input"
        .error-text
          - @user.errors.full_messages_for(:nickname).each do |message|
            %div
              = message
        .user-detail__top.form-content
          メールアドレス
        .user-detail__email-input
          = f.email_field :email, placeholder: "> email", class:"text-input"
        .error-text
          - @user.errors.full_messages_for(:email).each do |message|
            %div
              = message
        - if @sns_id.present?
          .user-detail__top.form-content.text-red
            生年月日
        - else
          .user-detail__top.form-content
            生年月日
        .user-detail__birthday-input
          != sprintf(f.date_select(:birth_day, prefix:'birth_day', with_css_classes:'select-box', prompt: "---",use_month_numbers:true, start_year:2020, end_year:1920, date_separator:'%s'),'年','月')+'日'
          .error-text
            - @user.errors.full_messages_for(:birth_day).each do |message|
              %div
                = message
        - if @sns_id.present?
          = hidden_field_tag :sns_auth, true
        - else
          .user-detail__top.form-content
            パスワード
          .user-detail__password-input
            = f.password_field :password, placeholder: "> password", class:"text-input"
          .error-text
            - @user.errors.full_messages_for(:password).each do |message|
              %div
                = message
      .btn-box.display-flex
        .btn-box__user-new
          = f.submit " 新規登録する ", class: "submit-btn text-line-none"
        .btn-box__back
          = link_to :back, class: "gray-btn margin-left-40 text-line-none" do
            もどる

app/views/signup/start_app.html.haml
.start-app.main-font
  .start-app__main.box-center
    = render "shared/content_top"
    .user-detail
      .user-detail__test.text-center
        ※テストアカウントがございます。ログインにお進みください。
    .btn-box
      .btn-box__user-new
        = link_to new_signup_path, class:"black-link-btn text-line-none" do
          新規会員登録
      .btn-box__user-login
        = link_to new_user_session_path, class:"white-link-btn text-line-none font-bold" do
          ログイン