config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root "home#index"
  resources :home, only: [:index] do
    collection do
      get 'app_description'
    end
  end
  resources :signup, only: [:new, :create] do
    collection do
      get 'logout'
      get 'start_app'
    end
  end
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'category'
      get 'novel'
      get 'management'
      get 'economy'
      get 'finance'
      get 'it'
      get 'motivation'
      get 'talent'
      get 'etc'
      get 'reread_timing'
      get 'timing_knowledge'
      get 'timing_motivation'
      get 'timing_decision'
      get 'timing_stress'
      get 'timing_feel_down'
      get 'timing_lost_love'
      get 'timing_diversion'
      get 'timing_relax'
      get 'all_books'
      get 'read_books'
      get 'will_read_books'
      get 'follow_book'
      get 'followings'
      get 'followers'
      get 'read_count_books'
      get 'read_history'
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :books do
    resources :impressions
    collection do
      get 'search'
    end
    member do
      get 'follow_book_show'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  mount_uploader :image, ImageUploader

  has_many :books
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  has_many :notices
  has_many :sns_credentials

  validates :nickname, presence: true
  validates :nickname, length: { maximum: 15, message: "は 15文字以下で入力してください" }, allow_blank: true
  validates :email, presence: true, uniqueness: true
  validates :birth_day, presence: true
  validates :birth_day, date: true, allow_blank: true

  scope :sorted, -> { order("created_at DESC") }

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
      email: auth.info.email
    )
    # userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    authorization
  end

  def failure
    redirect_to root_path
  end

  private

  def authorization
    sns_info = User.from_omniauth(request.env["omniauth.auth"])
    @user = sns_info[:user]
    if @user.persisted? # ユーザー情報が登録済みなので、新規登録ではなくログイン処理を行う
      sign_in_and_redirect @user, event: :authentication
    else # ユーザー情報が未登録なので、新規登録画面へ遷移する
      @sns_id = sns_info[:sns].id
      render 'signup/new'
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :birthday_add, only: [:update]
  before_action :set_user, :set_user_notice, only: [:show,
                                                    :edit,
                                                    :update,
                                                    :category,
                                                    :novel,
                                                    :management,
                                                    :economy,
                                                    :finance,
                                                    :it,
                                                    :motivation,
                                                    :talent,
                                                    :etc,
                                                    :reread_timing,
                                                    :timing_knowledge,
                                                    :timing_motivation,
                                                    :timing_decision,
                                                    :timing_stress,
                                                    :timing_feel_down,
                                                    :timing_lost_love,
                                                    :timing_diversion,
                                                    :timing_relax,
                                                    :all_books,
                                                    :read_books,
                                                    :will_read_books,
                                                    :follow_book,
                                                    :followings,
                                                    :followers,
                                                    :read_count_books,
                                                    :read_history]
  before_action :set_user_impression, only: [:show,
                                             :reread_timing,
                                             :timing_knowledge,
                                             :timing_motivation,
                                             :timing_decision,
                                             :timing_stress,
                                             :timing_feel_down,
                                             :timing_lost_love,
                                             :timing_diversion,
                                             :timing_relax,
                                             :read_count_books]

  def show
    @followers = @user.followers
    @followings = @user.followings
    @buy_books = @user.books.impression_none.sorted.limit(5)
    @read_books_impressions = @impressions.sorted.limit(5)
    @will_read_books = @user.books.book_following.sorted.limit(5)
    @read_count_impressions = @impressions.read_count.sorted.limit(5)
    # グラフ用の値の取り出し
    gon.novel = @user.books.category_novel.no_book_following.count
    gon.management = @user.books.category_management.no_book_following.count
    gon.economy = @user.books.category_economy.no_book_following.count
    gon.finance = @user.books.category_finance.no_book_following.count
    gon.it = @user.books.category_it.no_book_following.count
    gon.motivation = @user.books.category_motivation.no_book_following.count
    gon.talent = @user.books.category_talent.no_book_following.count
    gon.etc = @user.books.category_etc.no_book_following.count
  end

  def edit; end

  def update
    @user[:birth_day] = @birth_date.to_s
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def category
    @novels = @user.books.category_novel.no_book_following.sorted.limit(5)
    @managements = @user.books.category_management.no_book_following.sorted.limit(5)
    @economys = @user.books.category_economy.no_book_following.sorted.limit(5)
    @finances = @user.books.category_finance.no_book_following.sorted.limit(5)
    @its = @user.books.category_it.no_book_following.sorted.limit(5)
    @motivations = @user.books.category_motivation.no_book_following.sorted.limit(5)
    @talents = @user.books.category_talent.no_book_following.sorted.limit(5)
    @etcs = @user.books.category_etc.no_book_following.sorted.limit(5)
  end

  def novel
    @novels = @user.books.category_novel.no_book_following.sorted
  end

  def management
    @managements = @user.books.category_management.no_book_following.sorted
  end

  def economy
    @economys = @user.books.category_economy.no_book_following.sorted
  end

  def finance
    @finances = @user.books.category_finance.no_book_following.sorted
  end

  def it
    @its = @user.books.category_it.no_book_following.sorted
  end

  def motivation
    @motivations = @user.books.category_motivation.no_book_following.sorted
  end

  def talent
    @talents = @user.books.category_talent.no_book_following.sorted
  end

  def etc
    @etcs = @user.books.category_etc.no_book_following.sorted
  end

  def reread_timing
    @timing_knowledges = @impressions.knowledge
    @timing_motivations = @impressions.motivation
    @timing_decisions = @impressions.decision
    @timing_stresses = @impressions.stress
    @timing_feel_downs = @impressions.feel_down
    @timing_lost_loves = @impressions.lost_love
    @timing_diversions = @impressions.diversion
    @timing_relaxes = @impressions.relax
  end

  def timing_knowledge
    @timing_knowledges = @impressions.knowledge.sorted
  end

  def timing_motivation
    @timing_motivations = @impressions.motivation.sorted
  end

  def timing_decision
    @timing_decisions = @impressions.decision.sorted
  end

  def timing_stress
    @timing_stresses = @impressions.stress.sorted
  end

  def timing_feel_down
    @timing_feel_downs = @impressions.feel_down.sorted
  end

  def timing_lost_love
    @timing_lost_loves = @impressions.lost_love.sorted
  end

  def timing_diversion
    @timing_diversions = @impressions.diversion.sorted
  end

  def timing_relax
    @timing_relaxes = @impressions.relax.sorted
  end

  def all_books
    @all_books = @user.books.no_book_following.sorted
  end

  def read_books
    @read_books = @user.books.impression_exist.sorted
  end

  def will_read_books
    @will_read_books = @user.books.impression_none.sorted
  end

  def follow_book
    @follow_books = @user.books.book_following.sorted
  end

  def followings
    @users = @user.followings
  end

  def followers
    @users = @user.followers
  end

  def read_count_books
    @read_once_impressions = @impressions.read_once.sorted
    @read_twice_impressions = @impressions.read_twice.sorted
    @read_three_impressions = @impressions.read_three.sorted
  end

  def read_history
    @historys = Notice.search_user(@user.id).impression_register_exist.sorted
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :password, :birth_day, :image)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_user_notice
    @notices = Notice.search_user(@user.following_ids).last_seven_days.sorted.limit(10)
  end

  def set_user_impression
    @impressions = Impression.where(book_id: @user.books.ids)
  end

  def birthday_add
    if params[:birth_day]["birth_day(1i)"].present? && params[:birth_day]["birth_day(2i)"].present? && params[:birth_day]["birth_day(3i)"].present?
      birthday = params[:birth_day]
      @birth_date = Date.new(birthday["birth_day(1i)"].to_i, birthday["birth_day(2i)"].to_i, birthday["birth_day(3i)"].to_i)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/category.html.haml
= render "shared/mypage_header", user: @user
.category-top.main-font
  .category-top__main
    = render "shared/content_top"
    .category-top__main__category-tag.box-center.margin-top-60
      .category-top__main__category-tag__box.display-flex.box-center
        .category-btn.background-novel.text-center.novel-btn
          = link_to novel_user_path(@user), class: "text-line-none text-black" do
            小説
        .category-btn.background-management.text-center.margin-left-20.management-btn
          = link_to management_user_path(@user), class: "text-line-none text-black" do
            経営・戦略
        .category-btn.background-economy.text-center.margin-left-20.economy-btn
          = link_to economy_user_path(@user), class: "text-line-none text-black" do
            政治・経済
        .category-btn.background-finance.text-center.margin-left-20.finance-btn
          = link_to finance_user_path(@user), class: "text-line-none text-black" do
            ファイナンス
      .category-top__main__category-tag__box.display-flex.box-center
        .category-btn.background-it.text-center.it-btn
          = link_to it_user_path(@user), class: "text-line-none text-black" do
            IT
        .category-btn.background-motivation.text-center.margin-left-20.motivation-btn
          = link_to motivation_user_path(@user), class: "text-line-none text-black" do
            自己啓発
        .category-btn.background-talent.text-center.margin-left-20.talent-btn
          = link_to talent_user_path(@user), class: "text-line-none text-black" do
            タレント本
        .category-btn.background-etc.text-center.margin-left-20.etc-btn
          = link_to etc_user_path(@user), class: "text-line-none text-black" do
            その他
  - if @novels.present? == true || @managements.present? == true || @economys.present? == true || @finances.present? == true || @its.present? == true || @motivations.present? == true || @talents.present? == true || @etcs.present? == true
    = render partial: "shared/category_list", locals: {books: @novels}
    = render partial: "shared/category_list", locals: {books: @managements}
    = render partial: "shared/category_list", locals: {books: @economys}
    = render partial: "shared/category_list", locals: {books: @finances}
    = render partial: "shared/category_list", locals: {books: @its}
    = render partial: "shared/category_list", locals: {books: @motivations}
    = render partial: "shared/category_list", locals: {books: @talents}
    = render partial: "shared/category_list", locals: {books: @etcs}
  - else
    .category-top__none.box-center.text-center
      登録された本がありません

app/views/users/economy.html.haml
= render "shared/mypage_header", user: @user
.single-category.main-font
  .single-category__main.box-center
    .single-category__main__box
      .single-category__main__box__title.box-center.font-bold
        政治・経済の一覧
      .single-category__main__box__books
        = render partial: "shared/book_list", locals: {books: @economys}

app/views/users/followers.html.haml
= render "shared/user_follow_header", user: @user
.followings-top.main-font
  - if @users.present?
    .followings-top__main.box-list.box-center
      = render "shared/follow_user_list", users: @users
  - else
    .followings-top__none.text-center
      登録がありません

app/views/users/read_books.html.haml
= render "shared/mypage_header", user: @user
.single-category.main-font
  .single-category__main.box-center
    .single-category__main__box
      .single-category__main__box__title.box-center.font-bold.display-flex
        読書済みの本
        .link-btn
          = link_to all_books_user_path, class: "mini-green-link-btn text-line-none margin-left-20" do
            すべて
        .link-btn
          = link_to read_books_user_path, class: "mini-orange-link-btn text-line-none" do
            読書済み
        .link-btn
          = link_to will_read_books_user_path, class: "mini-green-link-btn text-line-none" do
            未読
      .single-category__main__box__books
        = render partial: "shared/book_list", locals: {books: @read_books}

app/views/users/read_count_books.html.haml
= render "shared/mypage_header", user: @user
.read-count-books.main-font
  .read-count-books__main.box-center
    .read-count-books__main__box.active
      .read-count-books__main__box__title.box-center.font-bold.display-flex
        読書回数別の一覧
        .once-set-tab.mini-orange-link-btn
          1回のみ
        .once-set-tab.mini-green-link-btn
          2回のみ
        .once-set-tab.mini-green-link-btn
          3回以上
      .read-count-books__main__box__books
        = render partial: "shared/book_timing_list", locals: {impressions: @read_once_impressions}
    .read-count-books__main__box
      .read-count-books__main__box__title.box-center.font-bold.display-flex
        読書回数別の一覧
        .twice-set-tab.mini-green-link-btn
          1回のみ
        .twice-set-tab.mini-orange-link-btn
          2回のみ
        .twice-set-tab.mini-green-link-btn
          3回以上
      .read-count-books__main__box__books
        = render partial: "shared/book_timing_list", locals: {impressions: @read_twice_impressions}
    .read-count-books__main__box
      .read-count-books__main__box__title.box-center.font-bold.display-flex
        読書回数別の一覧
        .three-set-tab.mini-green-link-btn
          1回のみ
        .three-set-tab.mini-green-link-btn
          2回のみ
        .three-set-tab.mini-orange-link-btn
          3回以上
      .read-count-books__main__box__books
        = render partial: "shared/book_timing_list", locals: {impressions: @read_three_impressions}
    

app/views/users/reread_timing.html.haml
= render "shared/mypage_header", user: @user
.reread-timing-top.main-font
  .reread-timing-top__main
    = render "shared/content_top"
    .reread-timing-top__main__timing-tag.box-center.margin-top-60
      .reread-timing-top__main__timing-tag__box.display-flex.box-center
        .timing-btn.background-green.text-center
          = link_to timing_knowledge_user_path(@user), class: "text-line-none text-white" do
            知識を付けたい時
        .timing-btn.background-green.text-center.margin-left-20
          = link_to timing_motivation_user_path(@user), class: "text-line-none text-white" do
            モチベーションをあげたい時
        .timing-btn.background-green.text-center.margin-left-20
          = link_to timing_decision_user_path(@user), class: "text-line-none text-white" do
            なにか決断をする時
        .timing-btn.background-green.text-center.margin-left-20
          = link_to timing_stress_user_path(@user), class: "text-line-none text-white" do
            ストレスが溜まっている時
      .reread-timing-top__main__timing-tag__box.display-flex.box-center
        .timing-btn.background-green.text-center
          = link_to timing_feel_down_user_path(@user), class: "text-line-none text-white" do
            落ち込んでいる時
        .timing-btn.background-green.text-center.margin-left-20
          = link_to timing_lost_love_user_path(@user), class: "text-line-none text-white" do
            失恋した時
        .timing-btn.background-green.text-center.margin-left-20
          = link_to timing_diversion_user_path(@user), class: "text-line-none text-white" do
            気分転換したい時
        .timing-btn.background-green.text-center.margin-left-20
          = link_to timing_relax_user_path(@user), class: "text-line-none text-white" do
            リラックスしたい時
  - if @timing_knowledges.present? == true || @timing_motivations.present? == true || @timing_decisions.present? == true || @timing_stresses.present? == true || @timing_feel_downs.present? == true || @timing_lost_loves.present? == true || @timing_diversions.present? == true || @timing_relaxes.present? == true
    = render partial: "shared/reread_timing_list", locals: {impressions: @timing_knowledges}
    = render partial: "shared/reread_timing_list", locals: {impressions: @timing_motivations}
    = render partial: "shared/reread_timing_list", locals: {impressions: @timing_decisions}
    = render partial: "shared/reread_timing_list", locals: {impressions: @timing_stresses}
    = render partial: "shared/reread_timing_list", locals: {impressions: @timing_feel_downs}
    = render partial: "shared/reread_timing_list", locals: {impressions: @timing_lost_loves}
    = render partial: "shared/reread_timing_list", locals: {impressions: @timing_diversions}
    = render partial: "shared/reread_timing_list", locals: {impressions: @timing_relaxes}
  - else
    .reread-timing-top__none.box-center.text-center
      登録された本がありません

app/views/users/timing_decision.html.haml
= render "shared/mypage_header", user: @user
.single-category.main-font
  .single-category__main.box-center
    .single-category__main__box
      .single-category__main__box__title.box-center.font-bold
        なにか決断をする時の一覧
      .single-category__main__box__books
        = render partial: "shared/book_timing_list", locals: {impressions: @timing_decisions}

app/views/users/timing_diversion.html.haml
= render "shared/mypage_header", user: @user
.single-category.main-font
  .single-category__main.box-center
    .single-category__main__box
      .single-category__main__box__title.box-center.font-bold
        気分転換したい時の一覧
      .single-category__main__box__books
        = render partial: "shared/book_timing_list", locals: {impressions: @timing_diversions}

app/views/users/timing_feel_down.html.haml
= render "shared/mypage_header", user: @user
.single-category.main-font
  .single-category__main.box-center
    .single-category__main__box
      .single-category__main__box__title.box-center.font-bold
        落ち込んでいる時の一覧
      .single-category__main__box__books
        = render partial: "shared/book_timing_list", locals: {impressions: @timing_feel_downs}

app/views/users/timing_knowledge.html.haml
= render "shared/mypage_header", user: @user
.single-category.main-font
  .single-category__main.box-center
    .single-category__main__box
      .single-category__main__box__title.box-center.font-bold
        知識を付けたい時の一覧
      .single-category__main__box__books
        = render partial: "shared/book_timing_list", locals: {impressions: @timing_knowledges}

app/views/users/timing_lost_love.html.haml
= render "shared/mypage_header", user: @user
.single-category.main-font
  .single-category__main.box-center
    .single-category__main__box
      .single-category__main__box__title.box-center.font-bold
        失恋した時の一覧
      .single-category__main__box__books
        = render partial: "shared/book_timing_list", locals: {impressions: @timing_lost_loves}

app/views/users/timing_relax.html.haml
= render "shared/mypage_header", user: @user
.single-category.main-font
  .single-category__main.box-center
    .single-category__main__box
      .single-category__main__box__title.box-center.font-bold
        リラックスしたい時の一覧
      .single-category__main__box__books
        = render partial: "shared/book_timing_list", locals: {impressions: @timing_relaxes}

app/views/users/timing_stress.html.haml
= render "shared/mypage_header", user: @user
.single-category.main-font
  .single-category__main.box-center
    .single-category__main__box
      .single-category__main__box__title.box-center.font-bold
        ストレスが溜まっている時の一覧
      .single-category__main__box__books
        = render partial: "shared/book_timing_list", locals: {impressions: @timing_stresses}

app/views/users/will_read_books.html.haml
= render "shared/mypage_header", user: @user
.single-category.main-font
  .single-category__main.box-center
    .single-category__main__box
      .single-category__main__box__title.box-center.font-bold.display-flex
        未読の本
        .link-btn
          = link_to all_books_user_path, class: "mini-green-link-btn text-line-none margin-left-20" do
            すべて
        .link-btn
          = link_to read_books_user_path, class: "mini-green-link-btn text-line-none" do
            読書済み
        .link-btn
          = link_to will_read_books_user_path, class: "mini-orange-link-btn text-line-none" do
            未読
      .single-category__main__box__books
        = render partial: "shared/book_list", locals: {books: @will_read_books}