config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root "home#index"
  resources :home, only: [:index] do
    collection do
      get 'app_description'
    end
  end
  resources :signup, only: [:new, :create] do
    collection do
      get 'logout'
      get 'start_app'
    end
  end
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'category'
      get 'novel'
      get 'management'
      get 'economy'
      get 'finance'
      get 'it'
      get 'motivation'
      get 'talent'
      get 'etc'
      get 'reread_timing'
      get 'timing_knowledge'
      get 'timing_motivation'
      get 'timing_decision'
      get 'timing_stress'
      get 'timing_feel_down'
      get 'timing_lost_love'
      get 'timing_diversion'
      get 'timing_relax'
      get 'all_books'
      get 'read_books'
      get 'will_read_books'
      get 'follow_book'
      get 'followings'
      get 'followers'
      get 'read_count_books'
      get 'read_history'
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :books do
    resources :impressions
    collection do
      get 'search'
    end
    member do
      get 'follow_book_show'
    end
  end
end

app/views/shared/_book_timing_list.html.haml
.book-list.box-center.main-font
  - if impressions.present?
    .book-list__main.box-list
      - impressions.each do |impression|
        .book-list__main__box.text-center.book-hover
          = link_to book_impressions_path(impression.book), class: "book-list__main__box__content text-line-none text-black" do
            - if impression.book.category == "novel"
              .book-category-tag.background-novel
                小説
            - elsif impression.book.category == "management"
              .book-category-tag.background-management
                経営
            - elsif impression.book.category == "economy"
              .book-category-tag.background-economy
                経済
            - elsif impression.book.category == "finance"
              .book-category-tag.background-finance
                金融
            - elsif impression.book.category == "it"
              .book-category-tag.background-it
                IT
            - elsif impression.book.category == "motivation"
              .book-category-tag.background-motivation
                自己啓発
            - elsif impression.book.category == "talent"
              .book-category-tag.background-talent
                タレント
            - else
              .book-category-tag.background-etc
                その他
            .book-status
              .book-status__title.font-bold.text-white
                読書済
            .book-shadow
            .book-image
              = image_tag impression.book.image.to_s, class: "image-set"
            .book-title
              = impression.book.title
  - else
    .book-list__none.text-center
      登録された本がありません

app/views/shared/_category_list.html.haml
- if books.present?
  .category-list.main-font
    .category-list__main.box-center
      - if books[0].category == "novel"
        .category-list__main__title.text-center.text-novel.border-novel.font-bold
          = books[0].category_i18n
      - elsif books[0].category == "management"
        .category-list__main__title.text-center.text-management.border-management.font-bold
          = books[0].category_i18n
      - elsif books[0].category == "economy"
        .category-list__main__title.text-center.text-economy.border-economy.font-bold
          = books[0].category_i18n
      - elsif books[0].category == "finance"
        .category-list__main__title.text-center.text-finance.border-finance.font-bold
          = books[0].category_i18n
      - elsif books[0].category == "it"
        .category-list__main__title.text-center.text-it.border-it.font-bold
          = books[0].category_i18n
      - elsif books[0].category == "motivation"
        .category-list__main__title.text-center.text-motivation.border-motivation.font-bold
          = books[0].category_i18n
      - elsif books[0].category == "talent"
        .category-list__main__title.text-center.text-talent.border-talent.font-bold
          = books[0].category_i18n
      - else
        .category-list__main__title.text-center.text-etc.border-etc.font-bold
          = books[0].category_i18n
      .category-list__main__box
        .category-list__main__box__list.display-flex
          - if books[0].status == "book_impression_exist"
            = link_to book_impressions_path(books[0]), class: "text-line-none text-black" do
              .category-big.book-hover
                - if books[0].category == "novel"
                  .category-big__book-category-tag.background-novel.text-center
                    小説
                - elsif books[0].category == "management"
                  .category-big__book-category-tag.background-management.text-center
                    経営
                - elsif books[0].category == "economy"
                  .category-big__book-category-tag.background-economy.text-center
                    経済
                - elsif books[0].category == "finance"
                  .category-big__book-category-tag.background-finance.text-center
                    金融
                - elsif books[0].category == "it"
                  .category-big__book-category-tag.background-it.text-center
                    IT
                - elsif books[0].category == "motivation"
                  .category-big__book-category-tag.background-motivation.text-center
                    自己啓発
                - elsif books[0].category == "talent"
                  .category-big__book-category-tag.background-talent.text-center
                    タレント
                - else
                  .category-big__book-category-tag.background-etc.text-center
                    その他
                .book-status
                  .book-status__title.font-bold.text-white
                    読書済
                .book-shadow
                .category-big__photo
                  = image_tag books[0].image.to_s, class: "image-set"
                .category-big__text.text-center
                  = books[0].title
          - elsif books[0].status == "book_impression_none"
            = link_to book_path(books[0]), class: "text-line-none text-black" do
              .category-big.book-hover
                - if books[0].category == "novel"
                  .category-big__book-category-tag.background-novel.text-center
                    小説
                - elsif books[0].category == "management"
                  .category-big__book-category-tag.background-management.text-center
                    経営
                - elsif books[0].category == "economy"
                  .category-big__book-category-tag.background-economy.text-center
                    経済
                - elsif books[0].category == "finance"
                  .category-big__book-category-tag.background-finance.text-center
                    金融
                - elsif books[0].category == "it"
                  .category-big__book-category-tag.background-it.text-center
                    IT
                - elsif books[0].category == "motivation"
                  .category-big__book-category-tag.background-motivation.text-center
                    自己啓発
                - elsif books[0].category == "talent"
                  .category-big__book-category-tag.background-talent.text-center
                    タレント
                - else
                  .category-big__book-category-tag.background-etc.text-center
                    その他
                .category-big__photo
                  = image_tag books[0].image.to_s, class: "image-set"
                .category-big__text.text-center
                  = books[0].title
          - else
          .category-small.display-flex.box-list
            - books.each.with_index(0) do |book, i|
              - if i >= 1 && i <= 4 && book.status == "book_impression_exist"
                = link_to book_impressions_path(book), class: "text-line-none text-black" do
                  .category-small__box.book-hover
                    - if books[0].category == "novel"
                      .category-small__box__book-category-tag.background-novel.text-center
                        小説
                    - elsif books[0].category == "management"
                      .category-small__box__book-category-tag.background-management.text-center
                        経営
                    - elsif books[0].category == "economy"
                      .category-small__box__book-category-tag.background-economy.text-center
                        経済
                    - elsif books[0].category == "finance"
                      .category-small__box__book-category-tag.background-finance.text-center
                        金融
                    - elsif books[0].category == "it"
                      .category-small__box__book-category-tag.background-it.text-center
                        IT
                    - elsif books[0].category == "motivation"
                      .category-small__box__book-category-tag.background-motivation.text-center
                        自己啓発
                    - elsif books[0].category == "talent"
                      .category-small__box__book-category-tag.background-talent.text-center
                        タレント
                    - else
                      .category-small__box__book-category-tag.background-etc.text-center
                        その他
                    .book-status
                      .book-status__title.font-bold.text-white
                        読書済
                    .book-shadow
                    .category-small__box__photo
                      = image_tag book.image.to_s, class: "image-set"
                    .category-small__box__text.text-center
                      = book.title
              - elsif i >= 1 && i <= 4 && book.status == "book_impression_none"
                = link_to book_path(book), class: "text-line-none text-black" do
                  .category-small__box.book-hover
                    - if books[0].category == "novel"
                      .category-small__box__book-category-tag.background-novel.text-center
                        小説
                    - elsif books[0].category == "management"
                      .category-small__box__book-category-tag.background-management.text-center
                        経営
                    - elsif books[0].category == "economy"
                      .category-small__box__book-category-tag.background-economy.text-center
                        経済
                    - elsif books[0].category == "finance"
                      .category-small__box__book-category-tag.background-finance.text-center
                        金融
                    - elsif books[0].category == "it"
                      .category-small__box__book-category-tag.background-it.text-center
                        IT
                    - elsif books[0].category == "motivation"
                      .category-small__box__book-category-tag.background-motivation.text-center
                        自己啓発
                    - elsif books[0].category == "talent"
                      .category-small__box__book-category-tag.background-talent.text-center
                        タレント
                    - else
                      .category-small__box__book-category-tag.background-etc.text-center
                        その他
                    .category-small__box__photo
                      = image_tag book.image.to_s, class: "image-set"
                    .category-small__box__text.text-center
                      = book.title
              - else
- else

app/views/shared/_content_top.html.haml
- if params[:controller] == "devise/sessions" && params[:action] == "new" || params[:controller] == "devise/sessions" && params[:action] == "create"
  .content-top
    .content-top__title.content-title
      = icon 'fas', 'sign-in-alt', class: 'icon-sign-in'
      ログイン
      -# = link_to user_google_oauth2_omniauth_authorize_path, method: :post, class:"google-link-btn font-bold text-line-none" do
      -#   Googleでログイン
      = render "shared/easy_login_btn"
- elsif params[:controller] == "signup" && params[:action] == "logout"
  .content-top
    .content-top__title.content-title
      = icon 'fas', 'sign-out-alt', class: 'icon-sign-out'
      ログアウト
- elsif params[:controller] == "signup" && params[:action] == "start_app"
  .content-top.text-center
    .content-top__title.content-title
      = icon 'fas', 'play', class: 'icon-play'
      アプリを始める
- elsif params[:controller] == "signup" && params[:action] == "new" || params[:controller] == "signup" && params[:action] == "create"
  .content-top
    .content-top__title.content-title
      = icon 'fas', 'user', class: 'icon-sign-out'
      新規会員登録
      -# = link_to user_google_oauth2_omniauth_authorize_path, method: :post, class:"google-link-btn font-bold text-line-none" do
      -#   Googleで登録する
- elsif params[:action] == "google_oauth2"
  .content-top
    .content-top__title.content-title
      = icon 'fas', 'user', class: 'icon-sign-out'
      新規会員登録
- elsif params[:controller] == "books" && params[:action] == "new" || params[:controller] == "books" && params[:action] == "create"
  .content-top
    .content-top__title.content-title
      = icon 'fas', 'book', class: 'icon-sign-out'
      本の登録
- elsif params[:controller] == "books" && params[:action] == "show"
  .content-top.display-flex
    .content-top__title.content-title
      = icon 'fas', 'book-open', class: 'icon-book'
      本の詳細
    - if user_signed_in? && current_user == @book.user
      .content-top__book-edit
        = link_to edit_book_path(@book), class:"mini-green-link-btn font-bold text-line-none" do
          編集する
    - else
- elsif params[:controller] == "impressions" && params[:action] == "new" || params[:controller] == "impressions" && params[:action] == "create"
  .content-top
    .content-top__title.content-title
      = icon 'fas', 'comment-dots', class: 'icon-sign-out'
      感想の登録
- elsif params[:controller] == "impressions" && params[:action] == "edit" || params[:controller] == "impressions" && params[:action] == "update"
  .content-top.display-flex
    .content-top__title.content-title
      = icon 'fas', 'edit', class: 'icon-book'
      感想の編集
    .content-top__book-destroy
      = link_to book_impression_path(@book), method: :delete, class:"mini-green-link-btn font-bold text-line-none" do
        削除する
- elsif params[:controller] == "impressions" && params[:action] == "index"
  .content-top.box-center
    .content-top__box.display-flex
      .content-top__box__title.content-title
        = icon 'fas', 'sticky-note', class: 'icon-sign-out'
        読書情報
- elsif params[:controller] == "impressions" && params[:action] == "show"
  .content-top.box-center
    .content-top__box.display-flex.box-center.text-center
      .content-top__box__title.content-title.margin-left-80
        = icon 'fas', 'book-reader', class: 'icon-sign-out'
        感想の詳細
      - if user_signed_in? && current_user == @book.user
        .content-top__book-edit
          = link_to edit_book_impression_path(@book, @impression), class:"mini-green-link-btn font-bold text-line-none" do
            編集する
      - else
- elsif params[:controller] == "books" && params[:action] == "edit" || params[:controller] == "books" && params[:action] == "update"
  .content-top.display-flex
    .content-top__title.content-title
      = icon 'fas', 'edit', class: 'icon-book'
      本の編集
    .content-top__book-destroy
      = link_to book_path(@book), method: :delete, class:"mini-green-link-btn font-bold text-line-none" do
        削除する
- elsif params[:controller] == "users" && params[:action] == "edit" || params[:controller] == "users" && params[:action] == "update"
  .content-top
    .content-top__title.content-title
      = icon 'fas', 'user-edit', class: 'icon-sign-out'
      ユーザー情報編集
- elsif params[:controller] == "users" && params[:action] == "category"
  .content-top
    .content-top__title.content-title.text-center
      = icon 'fas', 'bars', class: 'icon-sign-out'
      ジャンル一覧
- elsif params[:controller] == "users" && params[:action] == "reread_timing"
  .content-top
    .content-top__title.content-title.text-center
      = icon 'fas', 'bars', class: 'icon-sign-out'
      また読みたい時一覧
- elsif params[:controller] == "books" && params[:action] == "follow_book_show"
  .content-top
    .content-top__title.content-title.text-center
      = icon 'fas', 'bars', class: 'icon-sign-out'
      読みたいリスト
- elsif params[:controller] == "users" && params[:action] == "read_history"
  .content-top
    .content-top__title.content-title
      = icon 'fas', 'history', class: 'icon-sign-out'
      読書履歴
- else

app/views/shared/_header.html.haml
.header.main-font.text-center
  .header__box.box-center
    - if user_signed_in?
      .header__box__logo
        = link_to user_path(current_user), class:"text-line-none text-white" do
          BOOK BANK
    - else
      .header__box__logo
        = link_to root_path, class:"text-line-none text-white" do
          BOOK BANK
    %ul.header__box__content.text-center.box-center.display-flex
      - if user_signed_in?
        %li.header__box__content__text
          = link_to user_path(current_user), class:"header-text text-line-none text-gray" do
            マイページ
        %li.header__box__content__text
          = link_to new_book_path, class:"header-text text-line-none text-gray" do
            本の登録
        %li.header__box__content__text
          = link_to all_books_user_path(current_user), class:"header-text text-line-none text-gray" do
            登録一覧
        %li.header__box__content__search
          = form_with(url: search_books_path, local: true, method: :get, class: "search-form") do |f|
            = f.text_field :keyword, placeholder: "本を検索する", class: "search-input"
            = button_tag type: 'submit', class: 'search-btn' do
              = icon 'fas', 'search', class: 'search-icon text-gray'
        %li.header__box__content__text
          = link_to followings_user_path(current_user), class:"header-text text-line-none text-gray" do
            フォロー
        %li.header__box__content__text
          = link_to followers_user_path(current_user), class:"header-text text-line-none text-gray" do
            フォロワー
        %li.header__box__content__text
          = link_to logout_signup_index_path, class:"header-text text-line-none text-gray" do
            ログアウト
      - else
        %li.header__box__content__text
          = link_to start_app_signup_index_path, class:"header-text text-line-none text-gray" do
            本の登録
        %li.header__box__content__text
          = link_to books_path, class:"header-text text-line-none text-gray" do
            登録本一覧
        %li.header__box__content__search
          = form_with(url: search_books_path, local: true, method: :get, class: "search-form") do |f|
            = f.text_field :keyword, placeholder: "本を検索する", class: "search-input"
            = button_tag type: 'submit', class: 'search-btn' do
              = icon 'fas', 'search', class: 'search-icon text-gray'
        %li.header__box__content__text
          = link_to new_signup_path, class:"header-text text-line-none text-gray" do
            新規会員登録
        %li.header__box__content__text
          = link_to new_user_session_path, class:"header-text text-line-none text-gray" do
            ログイン

app/views/shared/_impression_list.html.haml
.impression-list
  .impression-list__note
  - if params[:controller] == "impressions" && params[:action] == "index"
    .impression-list__note__top
      .note-icon
        = icon 'fas', 'book-reader', class: 'icon-book'
      .note-title
        感想の一覧
    - @impressions.each do |impression|
      - if user_signed_in?
        = link_to book_impression_path(impression.book_id,impression), class: "text-line-none" do
          .impression-list__note__content.impression-hover
            .note-date.text-green.font-bold
              = simple_time(impression.created_at)
            .note-reread-timing.box-center.text-center.background-green.text-white
              = impression.reread_timing_i18n
            - if impression.note.present?
              .note-content.text-black
                = impression.note
            - else
              .note-content.text-black
                感想メモの登録がありません
      - else
        = link_to start_app_signup_index_path(impression.book_id,impression), class: "text-line-none" do
          .impression-list__note__content.impression-hover
            .note-date.text-green.font-bold
              = simple_time(impression.created_at)
            .note-reread-timing.box-center.text-center.background-green.text-white
              = impression.reread_timing_i18n
            - if impression.note.present?
              .note-content.text-black
                = impression.note
            - else
              .note-content.text-black
                感想メモの登録がありません
  - elsif params[:controller] == "impressions" && params[:action] == "show"
    .impression-list__note__top
      .note-icon
        = icon 'fas', 'book-reader', class: 'icon-book'
      .note-title
        その他の感想
    - @impressions.each do |impression|
      - if impression == @impression
        .impression-list__note__content
          .note-active.text-white.background-orange
            表示中
          .note-date.text-orange.font-bold
            = simple_time(impression.created_at)
          .note-reread-timing.box-center.text-center.background-orange.text-white
            = impression.reread_timing_i18n
          - if impression.note.present?
            .note-content.text-black
              = impression.note
          - else
            .note-content.text-black
              感想メモの登録がありません
      - else
        = link_to book_impression_path(impression.book_id,impression), class: "text-line-none" do
          .impression-list__note__content.impression-hover
            .note-date.text-green.font-bold
              = simple_time(impression.created_at)
            .note-reread-timing.box-center.text-center.background-green.text-white
              = impression.reread_timing_i18n
            - if impression.note.present?
              .note-content.text-black
                = impression.note
            - else
              .note-content.text-black
                感想メモの登録がありません
    

app/views/shared/_mypage_header.html.haml
.content-headdr.main-font
  .content-headdr__main
    .content-headdr__main__box.box-center
      .content-headdr__main__box__list.display-flex
        .mypage-title.font-bold
          MYPAGE
        .mypage-list.display-flex
          - if params[:controller] == "users" && params[:action] == "show"
            .mypage-list__link
              = link_to user_path(user), class: "text-green font-bold text-line-none" do
                トップ
          - else
            .mypage-list__link
              = link_to user_path(user), class: "text-black text-line-none content-header-btn" do
                トップ
          - if params[:controller] == "users" && params[:action] == "read_history"
            .mypage-list__link
              = link_to read_history_user_path(user), class: "text-green font-bold text-line-none" do
                読書履歴
          - else
            .mypage-list__link
              = link_to read_history_user_path(user), class: "text-black text-line-none content-header-btn" do
                読書履歴
          - if params[:action] == "all_books" || params[:action] == "read_books" || params[:action] == "will_read_books"
            .mypage-list__link
              = link_to all_books_user_path(user), class: "text-green font-bold text-line-none" do
                登録本
          - else
            .mypage-list__link
              = link_to all_books_user_path(user), class: "text-black text-line-none content-header-btn" do
                登録本
          - if params[:action] == "read_count_books"
            .mypage-list__link
              = link_to read_count_books_user_path(user), class: "text-green font-bold text-line-none" do
                読書回数
          - else
            .mypage-list__link
              = link_to read_count_books_user_path(user), class: "text-black text-line-none content-header-btn" do
                読書回数
          - if params[:controller] == "users" && params[:action] == "category" || params[:action] == "novel" || params[:action] == "management" || params[:action] == "economy" || params[:action] == "finance" || params[:action] == "it" || params[:action] == "motivation" || params[:action] == "talent" || params[:action] == "etc" 
            .mypage-list__link
              = link_to category_user_path(user), class: "text-green font-bold text-line-none" do
                ジャンル
          - else
            .mypage-list__link
              = link_to category_user_path(user), class: "text-black text-line-none content-header-btn" do
                ジャンル
          - if params[:controller] == "users" && params[:action] == "reread_timing" || params[:action] == "timing_knowledge" || params[:action] == "timing_motivation" || params[:action] == "timing_decision" || params[:action] == "timing_stress" || params[:action] == "timing_feel_down" || params[:action] == "timing_lost_love" || params[:action] == "timing_diversion" || params[:action] == "timing_relax"
            .mypage-list__link
              = link_to reread_timing_user_path(user), class: "text-green font-bold text-line-none" do
                また読みたい時
          - else
            .mypage-list__link
              = link_to reread_timing_user_path(user), class: "text-black text-line-none content-header-btn" do
                また読みたい時
          - if params[:controller] == "users" && params[:action] == "follow_book" || params[:controller] == "books" && params[:action] == "follow_book_show"
            .mypage-list__link
              = link_to follow_book_user_path(user), class: "text-green font-bold text-line-none" do
                読みたいリスト
          - else
            .mypage-list__link
              = link_to follow_book_user_path(user), class: "text-black text-line-none content-header-btn" do
                読みたいリスト
        - if user_signed_in?
          .user-link.display-flex
            .user-link__nickname-icon.text-orange
              = icon 'fas', 'user', class: 'icon-user-link'
            .user-link__nickname
              = link_to user_path(user), class: "text-black text-orange text-line-none content-header-user-btn" do
                = user.nickname
            .user-link__followings-icon.text-orange
              = icon 'fas', 'heart', class: 'icon-user-link'
            .user-link__followings.text-center
              = link_to followings_user_path(user), class: "text-black text-orange text-line-none content-header-user-btn" do
                = user.followings.count
            .user-link__followers-icon.text-orange
              = icon 'fas', 'check', class: 'icon-user-link'
            .user-link__followers.text-center
              = link_to followers_user_path(user), class: "text-black text-orange text-line-none content-header-user-btn" do
                = user.followers.count
            - if current_user == user
              .user-link__news-icon.text-blue.news-list.text-center
                = icon 'fas', 'bell', class: 'icon-user-link'
              = render "shared/news_list"
        - else
          .user-link.display-flex
            .user-link__nickname-icon.text-orange
              = icon 'fas', 'user', class: 'icon-user-link'
            .user-link__nickname
              = link_to start_app_signup_index_path, class: "text-black text-orange text-line-none content-header-user-btn" do
                = user.nickname
            .user-link__followings-icon.text-orange
              = icon 'fas', 'heart', class: 'icon-user-link'
            .user-link__followings.text-center
              = link_to start_app_signup_index_path, class: "text-black text-orange text-line-none content-header-user-btn" do
                = user.followings.count
            .user-link__followers-icon.text-orange
              = icon 'fas', 'check', class: 'icon-user-link'
            .user-link__followers.text-center
              = link_to start_app_signup_index_path, class: "text-black text-orange text-line-none content-header-user-btn" do
                = user.followers.count

app/views/shared/_news_list.html.haml
.news-list-main.main-font
  .news-list-main__title.text-center.text-blue
    News
  - if @notices.present?
    - @notices.each do |notice|
      - if notice.impression_id.present?
        =link_to book_impression_path(notice.book_id, notice.impression_id), class: "news-list-main__box text-blue text-line-none" do
          .news-list-main__box__content
            = notice.news_text
          .news-list-main__box__dete
            = icon 'fas', 'clock', class: 'icon-user-link'
            = notice.days_elapsed
      - else
        =link_to book_path(notice.book_id), class: "news-list-main__box text-blue text-line-none" do
          .news-list-main__box__content
            = notice.news_text
          .news-list-main__box__dete
            = icon 'fas', 'clock', class: 'icon-user-link'
            = notice.days_elapsed
  - else
    .news-list-main__none.text-blue.text-center
      Newsがありません

app/views/shared/_user_follow_header.html.haml
.content-headdr.main-font
  .content-headdr__main
    .content-headdr__main__box.box-center
      .content-headdr__main__box__list.display-flex
        .follow-info-title.font-bold
          USER FOLLOW
        .follow-info-list.display-flex
          - if params[:controller] == "users" && params[:action] == "followings"
            .follow-info-list__link
              = link_to followings_user_path(user), class: "text-green font-bold text-line-none" do
                フォロー
          - else
            .follow-info-list__link
              = link_to followings_user_path(user), class: "text-black text-line-none content-header-btn" do
                フォロー
          - if params[:controller] == "users" && params[:action] == "followers"
            .follow-info-list__link
              = link_to followers_user_path(user), class: "text-green font-bold text-line-none" do
                フォロワー
          - else params[:controller] == "users" && params[:action] == "followers"
            .follow-info-list__link
              = link_to followers_user_path(user), class: "text-black text-line-none content-header-btn" do
                フォロワー
          .user-link.display-flex
            .user-link__nickname-icon.text-orange
              = icon 'fas', 'user', class: 'icon-user-link'
            .user-link__nickname
              = link_to user_path(user), class: "text-black text-orange text-line-none content-header-user-btn" do
                = user.nickname
            .user-link__followings-icon.text-orange
              = icon 'fas', 'heart', class: 'icon-user-link'
            .user-link__followings.text-center
              = link_to followings_user_path(user), class: "text-black text-orange text-line-none content-header-user-btn" do
                = user.followings.count
            .user-link__followers-icon.text-orange
              = icon 'fas', 'check', class: 'icon-user-link'
            .user-link__followers.text-center
              = link_to followers_user_path(user), class: "text-black text-orange text-line-none content-header-user-btn" do
                = user.followers.count
            - if current_user == user
              .user-link__news-icon.text-blue.news-list.text-center
                = icon 'fas', 'bell', class: 'icon-user-link'
              = render "shared/news_list"